name: razorpay_x_dhiwise
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.5
  connectivity_plus: ^2.3.6
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^0.22.0
  table_calendar: ^3.0.6
  url_launcher: 6.0.20
  fluttertoast: ^8.0.8
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Mulish
      fonts: 
        - asset: assets/fonts/MulishRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/MulishRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/MulishRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/MulishRomanBold.ttf
          weight: 700
